CREATE TABLE REPORTE_SOCIOS_ENTRENADOR_PART (
    REPORTE_ID INT NOT NULL,
    FECHA_REPORTE DATE NOT NULL,
    ENTRENADOR_ID VARCHAR(10) NOT NULL,
    ENTRENADOR VARCHAR(100) NOT NULL,
    CANTIDAD_SOCIOS INT NOT NULL,

    PRIMARY KEY (REPORTE_ID, FECHA_REPORTE)
)
PARTITION BY RANGE (YEAR(FECHA_REPORTE)) (
    PARTITION p2025 VALUES LESS THAN (2026),
    PARTITION p2026 VALUES LESS THAN (2027),
    PARTITION p2027 VALUES LESS THAN (2028),
    PARTITION p2028 VALUES LESS THAN (2029),
    PARTITION p_futuro VALUES LESS THAN MAXVALUE
);