CREATE DATABASE db_gym_records;
USE db_gym_records;

-- ============================================
-- CREACIÓN DE TABLAS - GIMNASIO NORMALIZADO
-- ============================================

-- 1. TABLA CIUDAD
CREATE TABLE CIUDAD (
    CIUDAD_ID VARCHAR(10) PRIMARY KEY,
    Ciudad_Sede VARCHAR(100) NOT NULL
);

-- 2. TABLA SEDE
CREATE TABLE SEDE (
    SEDE_ID VARCHAR(10) PRIMARY KEY,
    Gimnasio_Sede VARCHAR(100) NOT NULL,
    Ciudad_Sede VARCHAR(10) NOT NULL,
    
    CONSTRAINT FK_SEDE_CIUDAD
        FOREIGN KEY (Ciudad_Sede) REFERENCES CIUDAD(CIUDAD_ID)
);

-- 3. TABLA SOCIOS
CREATE TABLE SOCIOS (
    Socio_ID INT PRIMARY KEY,
    Nombre_Socio VARCHAR(100) NOT NULL,
    Apellidos VARCHAR(100) NOT NULL,
    Telefono VARCHAR(20)
);

-- 4. TABLA PLAN_ENTRENAMIENTO
CREATE TABLE PLAN_ENTRENAMIENTO (
    Plan_Entrenamiento_ID VARCHAR(10) PRIMARY KEY,
    Plan_Entrenamiento VARCHAR(100) NOT NULL
);

-- 5. TABLA ESPECIALIDAD
CREATE TABLE ESPECIALIDAD (
    ESPECIALIDAD_ID VARCHAR(10) PRIMARY KEY,
    Especialidad_Entrenador VARCHAR(100) NOT NULL
);

-- 6. TABLA ENTRENADORES
CREATE TABLE ENTRENADORES (
    Entrenadores_Asignados_ID VARCHAR(10) PRIMARY KEY,
    Entrenadores_Asignados VARCHAR(100) NOT NULL,
    ESPECIALIDAD_ID VARCHAR(10) NOT NULL,

    CONSTRAINT FK_ENTRENADORES_ESPECIALIDAD
        FOREIGN KEY (ESPECIALIDAD_ID)
        REFERENCES ESPECIALIDAD(ESPECIALIDAD_ID)
);

-- socio_plan_entrenamiento
CREATE TABLE SOCIO_PLAN_ENTRENAMIENTO (
    SOCIO_PLAN_ENTRENAMIENTO_ID INT PRIMARY KEY,
    Socio_ID INT NOT NULL,
    Plan_Entrenamiento_ID VARCHAR(10) NOT NULL,
    Entrenadores_Asignados_ID VARCHAR(10) NOT NULL,
    SEDE_ID VARCHAR(10) NOT NULL,

    CONSTRAINT FK_SPE_SOCIO
        FOREIGN KEY (Socio_ID)
        REFERENCES SOCIOS(Socio_ID),

    CONSTRAINT FK_SPE_PLAN
        FOREIGN KEY (Plan_Entrenamiento_ID)
        REFERENCES PLAN_ENTRENAMIENTO(Plan_Entrenamiento_ID),

    CONSTRAINT FK_SPE_ENTRENADOR
        FOREIGN KEY (Entrenadores_Asignados_ID)
        REFERENCES ENTRENADORES(Entrenadores_Asignados_ID),

    CONSTRAINT FK_SPE_SEDE
        FOREIGN KEY (SEDE_ID)
        REFERENCES SEDE(SEDE_ID)
);