CREATE TABLE IF NOT EXISTS REPORTE_SOCIOS_ENTRENADOR (
    REPORTE_ID INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_REPORTE DATE NOT NULL,
    ENTRENADOR_ID VARCHAR(10) NOT NULL,
    ENTRENADOR VARCHAR(100) NOT NULL,
    CANTIDAD_SOCIOS INT NOT NULL
);